version: "3"
services:

  tracking_mongo:
    image: mongo
    container_name: tracking_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: tracking
      MONGO_INITDB_ROOT_PASSWORD: tracking
    volumes:
      - tracking_mongo:/data/db
    ports:
      - "27017:27017"

  tracking_mrw:
    build: .

volumes:
  tracking_mongo: