version: "3"
services:

  tracking_mrw:
    build: .

  tracking_mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: tracking
      MONGO_INITDB_ROOT_PASSWORD: tracking
    volumes:
      - tracking_mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  tracking_mongo: